#!/bin/bash
#BASH
alias qq='nano /home/admin-extra/.bash_aliases'
alias reload='source /home/admin-extra/.bash_aliases'

#NETPLAN COMMANDS
alias netpl='sudo nano /etc/netplan/00-installer-config.yaml'
alias nreload='sudo netplan apply'

#CONNECT TO THE MACHINES
alias dh='ssh admin-extra@192.168.100.2'

#IPTABLE COMMANDS
alias ff='sudo nano /etc/ufw/before.rules'
alias tt='sudo iptables -t nat -L'

############
#DHCP SERVER
alias dhcpdconf='sudo nano /etc/dhcp/dhcpd.conf'
alias dreload='sudo systemctl restart isc-dhcp-server'
alias dstatus='sudo systemctl status isc-dhcp-server'
############

alias gethub='rm ./bash | git clone https://github.com/loglist22/bash/ | cp ./bash/gw ./.bash_aliases'

#sudo apt upgrade openvswitch-switch
