#!/bin/bash
#BASH
alias qq='nano /home/admin-extra/.bash_aliases'
alias reload='source /home/admin-extra/.bash_aliases'

#NETPLAN COMMANDS
alias netpl='sudo nano /etc/netplan/00-installer-config.yaml'
alias nreload='sudo netplan apply'

#CONNECT TO THE MACHINES
alias dh='ssh admin-extra@192.168.100.2'

#IPTABLE COMMANDS
alias ff='sudo nano /etc/ufw/before.rules'
alias tt='sudo iptables -t nat -L'
